### PR TITLE
Add a doc for some general good Git practices

### PR DESCRIPTION
**Pull request by uddinmehrab**

### CODE REVIEW

**Comment by TommyOh0428** [comment]
can you add

---
sidebar_position: 7
---
at the top of your md file

**Comment by Seanspoons** [comment]
This is almost the exact same as the content of the other git docs. Is it necessary as a separate section?

**Comment by uddinmehrab** [comment]
> This is almost the exact same as the content of the other git docs. Is it necessary as a separate section? Could some of the content that is new be added into the other git doc sections?

The other Git docs focus more on how-to instructions, while this section provides a quick list of best practices to keep in mind when learning and using Git. I believe it would be helpful for beginners as a supplement to the technical guides.

**Comment by Seanspoons** [comment]
The only thing is almost all the information in this PR is in the Club-Specific Guidlines section in an easy to read format already. Do you think you could take the stuff that isn't in that section such as .gitignore and not putting sensitive information and create a section on that. It would be great to have an expanded section on .gitignore and not putting API keys, environment variables and that sort've thing in repositories. Then we would have both bases covered. What are your thoughts?

**Comment by uddinmehrab** [comment]
Can do, I didn't fully read through the club guidelines section. I'll create a new PR specifically for .gitignore and some other helpful info that you mentioned.

**Comment by Seanspoons** [comment]
Thanks, that will be very helpful as I remember not using .gitignore at all or not properly when I was just starting. This will be hugely valuable!

**Pull request closed without merging**
