### PR TITLE
Add doc on code styling

### PR DESCRIPTION
**Pull request by uddinmehrab**
Saw an issue open for this, so adding a tutorial extra on good code styling practices for beginners.

### CODE REVIEW

**Comment by TommyOh0428** [comment]
do you mind make a separate folder and split the chapters like
section for bad code styling
what is good code styling, etc

**Comment by uddinmehrab** [comment]
Like examples for bad code styling in one section and another section for good code styling? Wouldn't it be more beneficial to have it all in one doc so that they can directly see the differences?

I'm not exactly sure what I should split , so if you have ideas on which part of the doc should be split to go where, that would be great.

**Comment by uddinmehrab** [comment]
> do you mind making a separate folder name like code styling and splitting the chapters like section for bad code styling what is good code styling, etc

Ignore my deleted reply, didn't realize what you meant. Do you want the folder to be under tutorial extras? I feel it would be beneficial to have it all in one doc.

**Comment by TommyOh0428** [comment]
what i meant is instead of working on tutorial-extra folder that are existing in the directory, make new folder section called code styling and start making chapters inside. Look at the code structure for git section

**Comment by uddinmehrab** [comment]
Ah, I understand now. Will do.

**Pull request closed without merging**
